spring:
  application:
    name: eChat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/chat
    username: balamut
    password: maksym
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    web: trace
    org.springframework.security: trace
