spring:
  application:
    name: eChat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat
    username: balamut
    password: maksym
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: E4F56E4FDC9BDCA24F48C9B56EED0DED4942372A744D8651290B5713AEA876DF
      expiration: 86400000
      refresh-token:
        expiration: 604800000
